### ISSUE TITLE
Last.fm keeps losing authentication

### ISSUE THREAD

**Issue by exptom** [strawberrymusicplayer/strawberry#442]
**Describe the bug**
Last.fm loses authentication multiple times a day. If I click "close" on the dialog box it kills strawberry.
Each time it happens I have to use the "Login" button in the settings dialogue to reconnect to last.fm. I have tried with both the "HTTPS for local redirectserver" enabled and disabled.

**To Reproduce**
Authenticate with Last.fm and start playing music, eventually the message appears, I can't see a pattern so far. It has happened after 2 songs and after dozens!

**Screenshots:**
![Screenshot at 2020-05-26 14-47-07](https://user-images.githubusercontent.com/4302032/82908520-fe935780-9f5f-11ea-8134-1abb41fa3830.png)

**System Information:**
 - Operating system: Ubuntu 18.04
 - Strawberry Version: 0.6.11

**Comment by jonaski** [comment]
It clears the login when an error is received from last.fm that the session is expired. It works fine for me without expiring. You should be able to se the actual error returned by last.fm if you run strawberry from the terminal.
I suggest you open an issue to last.fm: https://www.last.fm/about/contact

**Comment by exptom** [comment]
It had been working fine for me prior to the day before I reported this issue. Now it keeps happening very frequently. The message on the terminal is as follows:

```
14:27:07.770 DEBUG AudioScrobbler:147               Scrobbling song "片岡真央" "The Legend of Zelda: Breath of the Wild - Original Soundtrack [Limited Edition]" "華麗なるウルボザ" at 73
14:27:07.770 DEBUG ScrobblingAPI20:562              "Last.fm" Submitting scrobbles.
14:27:10.486 ERROR ScrobblingAPI20:987              "Last.fm" "Authentication Failed - You do not have permissions to access the service (4)"
```

**Comment by RomanHargrave** [comment]
@jonaski I'm now encountering the same issue as exptom about every ten minutes. I have reconnected to last.fm about 20 times today. I'm not entirely sure what the cause is.

**Comment by jonaski** [comment]
I have experienced the same thing yesterday and today, but I have been playing music on 2 computers at the same time with enabled scrobbling, I don't know if it could be related to that.
Last.fm returns - "4 : Authentication Failed - You do not have permissions to access the service"
Reference: https://www.last.fm/api/errorcodes
I assume that means that the session isn't valid anymore and we should clear the session so that the user needs to re-login.

Did any of you ask on the support forum?

I asked now:
https://support.last.fm/t/4-authentication-failed-you-do-not-have-permissions-to-access-the-service/2724

**Comment by NucleaPeon** [comment]
**My Experience:**
I only scrobble on one machine, I had to reconnect to last.fm once, about a week ago, and haven't seen it since.
I was on 0.6.12 until the last 3-4 days, updated to 0.6.13 (gentoo). No issues there.

I did at one point prior leave scrobbling on without being connected to the internet. I played through 30-40 songs with the error popping up that I ignored.

**Comment by jonaski** [comment]
If you don't mind compiling from source you can try removing this line in ScrobblingAPI20::GetReplyData in https://github.com/strawberrymusicplayer/strawberry/blob/master/src/scrobbler/scrobblingapi20.cpp
`error_code == ScrobbleErrorCode::AuthenticationFailed ||`
Then it won't clear the session in case of the API error 4, but try resend the scrobbles in regular intervals using the same session id. Watch the scrobbling and see if the error occurs again or is resolved by itself.

**Comment by RomanHargrave** [comment]
I'll check this. I was actually just reading the API documentation today with the intention of creating a patch and saw that, in the scrobble flow, the only error code that required invalidating the session was 9.

**Comment by jonaski** [comment]
I'd like to see that it actually is a temporary problem, and the login is not invalidated, before we remove the clearing of the session token, otherwise it will continue to resend the same scrobbles and the user will not be notified if the error dialog is disabled. So far no answer from last.fm.

**Comment by RomanHargrave** [comment]
I have not encountered any issues so far today and don not appear to be missing scrobbles. I'm using a copy of strawberry built at commit 1d439e67.

**Comment by jonaski** [comment]
I found a couple of bugs but I doubt they were related to this.
It was starting the array notation at 1 instead of 0, which is why last.fm always replied 1 ignored scrobble, which actually was for array 0 since I had incorrectly started at 1.
trackNumber was sent incorrectly.
Both fixed now.

**Comment by jonaski** [comment]
I can't reproduce the "4 : Authentication Failed - You do not have permissions to access the service" problem anymore.
Last.fm did not reply, but I see that there were a lot of similar related issues reported around the same time.
I'm a bit resistant to removing the clearing of the token unless we know for certain that a new login isn't required, in case it's permanent error that require a new login, the user won't know if they disable the error dialog in the setting.

**Comment by NyaomiDEV** [comment]
I can still reproduce this behaviour four years later - probably it's just wise to keep the session or to prompt for a login whenever the error happens.

**Comment by jonaski** [comment]
The problem is that last.fm returns the "4 - Authentication Failed" when their servers are overloaded, so the real issue is with last.fm, not strawberry. Still no reply from last.fm after 4 years: https://support.last.fm/t/4-authentication-failed-you-do-not-have-permissions-to-access-the-service/2724
Keeping the session will keep sending scrobbles so that will result in even more requests to their servers, which won't help when the servers already has issues. But I've removed clearing the token for last.fm error 4 and some of the network errors that are related to that, so we'll see how that goes, but I suspect it's a bad idea.
